import { Link } from 'react-router-dom'
import { useEffect } from 'react'
import TopBar from './components/TopBar'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const benefits = [
  { icon: 'fa-chart-line', title: 'Enhanced Business Value', desc: 'BRSR reporting strengthens your company\'s value proposition by demonstrating commitment to sustainable and responsible business practices.' },
  { icon: 'fa-coins', title: 'Access to Capital', desc: 'Increased access to capital investment as ESG-conscious investors and financial institutions prioritize companies with robust sustainability disclosures.' },
  { icon: 'fa-shield-alt', title: 'Lowered Risk', desc: 'Not only within your own operations but also within your supply chain, among subsidiaries, or within your own investment portfolio.' },
  { icon: 'fa-landmark', title: 'Enhanced Corporate Governance', desc: 'Strengthen your corporate governance framework through transparent ESG reporting and accountability mechanisms.' },
  { icon: 'fa-users', title: 'Attracting Talent & Investor Confidence', desc: 'Build investor confidence and attract top talent who value organizations committed to sustainability and responsible business conduct.' }
]

const mandatoryVerification = [
  { icon: 'fa-bolt', text: 'Electricity Consumption, water usage, air emissions' },
  { icon: 'fa-user-shield', text: 'Human rights, minimum and fair wages' },
  { icon: 'fa-balance-scale', text: 'Anti-corruption, anti-bribery and conflicts of interest policies' },
  { icon: 'fa-baby-carriage', text: 'Parental benefits, employee accessibility' }
]

const eurocertBenefits = [
  { icon: 'fa-leaf', text: 'Valuation of "Green Credits" generated by the company and the value chain partners' },
  { icon: 'fa-globe-europe', text: 'BRSR Verification will be scaled on the accumulative of foreign agencies offering ESG ratings and international frameworks such as TCFD, GRI or CDP for which Eurocert SA auditors are competent.' },
  { icon: 'fa-gavel', text: 'Verifications are done by members and auditors with experience under FATF and are recognized under respective laws' }
]

const verificationServices = [
  { icon: 'fa-clipboard-check', title: 'Essential & Leadership Indicators', desc: 'Eurocert SA verify your mandatory Essential Indicators (EI) and voluntary Leadership Indicators (LI) disclosures.' },
  { icon: 'fa-star', title: 'Scoring Verification', desc: 'Eurocert SA verifies your Transition or Parivartan Score, Combined Score, Core Transition or Parivartan Score, Core Combined Score.' }
]

const assessmentAreas = [
  { icon: 'fa-file-alt', title: 'A — General Disclosures', desc: 'Comprehensive verification of general organizational disclosures and reporting.' },
  { icon: 'fa-sitemap', title: 'B — Management & Process Disclosures', desc: 'Including Leadership & Governance frameworks and management processes.' },
  { icon: 'fa-user-check', title: 'C — Individual Verification', desc: 'Detailed verification across specific ESG parameters and indicators.' }
]

const individualVerificationItems = [
  { icon: 'fa-handshake', text: 'Ethics, Transparency and Accountability' },
  { icon: 'fa-ban', text: 'Anti-corruption or anti-bribery, Conflict of Interest' },
  { icon: 'fa-recycle', text: 'Sustainability and Extended Producer Responsibility' },
  { icon: 'fa-hard-hat', text: 'Health & Safety management' },
  { icon: 'fa-fist-raised', text: 'Human Rights' },
  { icon: 'fa-bolt', text: 'Energy, water Consumption' },
  { icon: 'fa-smog', text: 'Emissions: Air including Scope 1, 2 & 3' },
  { icon: 'fa-trash-alt', text: 'Waste Management' },
  { icon: 'fa-seedling', text: 'Social &/or Environmental Impact Assessment' }
]

const relatedServices = [
  { title: 'ISO 14064', subtitle: 'GHG Quantification & Verification', image: '/s2.png', link: '/management-system/iso-14064' },
  { title: 'Carbon Footprint', subtitle: 'GHG Assessment Services', image: '/s3.png', link: '/sustainability/carbon-footprint' },
  { title: 'Sustainability Certifications', subtitle: 'Environmental Certifications', image: '/h4.png', link: '/sustainability/certifications' }
]

export default function BRSR() {
  useEffect(() => { window.scrollTo(0, 0) }, [])

  return (
    <div>
      <TopBar />
      <Navbar />

      {/* Hero - Dark */}
      <section className="relative min-h-[55vh] flex items-center justify-center overflow-hidden bg-[#030a16]">
        <div className="absolute inset-0 z-0">
          <img src="/bb1.png" className="w-full h-full object-cover opacity-30" alt="BRSR Reporting" />
          <div className="absolute inset-0 bg-linear-to-b from-[#030a16]/70 via-[#030a16]/40 to-[#030a16]"></div>
        </div>
        <div className="container mx-auto px-6 relative z-10 text-center py-20">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-eurogold-400/30 bg-eurogold-400/5 mb-6">
            <span className="w-1.5 h-1.5 rounded-full bg-eurogold-400 animate-pulse"></span>
            <span className="heading-font text-[10px] text-eurogold-400 tracking-[0.3em] uppercase font-bold">ESG Disclosure, Verification & Sustainability Reporting</span>
          </div>
          <h1 className="heading-font text-4xl sm:text-6xl md:text-7xl font-bold text-white mb-3 tracking-tight" style={{ textShadow: '0 0 30px rgba(212,168,67,0.3)' }}>
            BRSR <span className="text-eurogold-400">Reporting</span>
          </h1>
          <p className="text-white/50 text-sm md:text-base max-w-2xl mx-auto leading-relaxed">
            Business Responsibility & Sustainability Reporting — Mandatory ESG disclosure and third-party verification
          </p>
        </div>
      </section>

      {/* Intro + What Is - Light */}
      <section className="py-14 lg:py-18 bg-white">
        <div className="container mx-auto px-6">
          <div className="grid lg:grid-cols-5 gap-10 items-start">
            <div className="lg:col-span-3 space-y-6">
              <div>
                <h4 className="heading-font text-[11px] text-euro-600 tracking-[0.5em] uppercase mb-2 font-bold">What Most People Know</h4>
                <h2 className="heading-font text-3xl md:text-4xl font-bold text-slate-900 tracking-tight leading-tight">
                  Business Responsibility & <span className="text-euro-600">Sustainability Reporting (BRSR)</span>
                </h2>
              </div>
              <div className="p-6 rounded-2xl border border-euro-100 bg-euro-50/40">
                <div className="flex items-center gap-3 mb-3">
                  <div className="w-9 h-9 rounded-xl bg-euro-600 flex items-center justify-center">
                    <i className="fas fa-question-circle text-white text-xs"></i>
                  </div>
                  <h4 className="heading-font text-[11px] text-euro-600 font-bold uppercase tracking-widest">What Most People Don't Know — Why You Need BRSR</h4>
                </div>
                <p className="text-slate-500 text-sm leading-relaxed mb-3">
                  In addition to complying with BRSR, the top 150 companies (by market capitalisation) are mandated to report their sustainability performance in the BRSR Core format from FY 2023–24. The applicability of BRSR Core will gradually increase from 150 companies in FY 2023–24 to 1000 by FY 2026–27.
                </p>
                <p className="text-slate-500 text-sm leading-relaxed mb-3">
                  In addition, the top 250 listed companies are mandated to disclose the ESG footprint of their value chain from FY 2024–25 and obtain assurance through third-party auditors on a comply-or-explain basis from FY 2025–26.
                </p>
                <p className="text-slate-500 text-sm leading-relaxed mb-3">
                  As per Ministry of Corporate Affairs (MCA) committee recommendation, the reporting requirement may be extended by MCA to unlisted companies based on specified thresholds of turnover or paid-up capital.
                </p>
                <p className="text-slate-500 text-sm leading-relaxed">
                  Further ESG disclosures for the value chain shall be applicable to the top 250 listed entities (by market capitalization), on a comply-or-explain basis from FY 2024-25. Further the reports other than BRSR also needs to be verified as per SEBI standards.
                </p>
              </div>
            </div>
            <div className="lg:col-span-2 relative rounded-2xl overflow-hidden shadow-xl border border-slate-100 h-[320px] md:h-[400px] group">
              <img src="/bb1.png" className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" alt="BRSR Reporting" />
              <div className="absolute inset-0 bg-linear-to-t from-slate-900/20 via-transparent to-transparent"></div>
            </div>
          </div>
        </div>
      </section>

      {/* Benefits of BRSR - Soft BG */}
      <section className="py-14 lg:py-18 bg-[#f8fafc]">
        <div className="container mx-auto px-6">
          <div className="text-center mb-10">
            <h4 className="heading-font text-[11px] text-euro-600 tracking-[0.5em] uppercase mb-2 font-bold">Why BRSR Matters</h4>
            <h2 className="heading-font text-3xl md:text-4xl font-bold text-slate-900 tracking-tight">
              The Benefits of <span className="text-euro-600">BRSR Reporting</span>
            </h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-5 max-w-6xl mx-auto">
            {benefits.map((b, i) => (
              <div key={i} className="p-6 bg-white rounded-2xl border border-slate-100 hover:border-euro-200 hover:shadow-lg transition-all duration-300 group text-center">
                <div className="w-12 h-12 rounded-xl bg-euro-50 flex items-center justify-center text-euro-600 mb-4 mx-auto group-hover:bg-euro-600 group-hover:text-white transition-all duration-300">
                  <i className={`fas ${b.icon} text-lg`}></i>
                </div>
                <h4 className="heading-font text-[11px] font-bold uppercase tracking-widest text-slate-900 mb-2">{b.title}</h4>
                <p className="text-slate-400 text-sm leading-relaxed">{b.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Mandatory Verification + Eurocert Benefits - Light */}
      <section className="py-14 lg:py-18 bg-white">
        <div className="container mx-auto px-6">
          <div className="grid lg:grid-cols-2 gap-10 max-w-5xl mx-auto">
            {/* Mandatory Verification */}
            <div>
              <div className="mb-6">
                <h4 className="heading-font text-[11px] text-euro-600 tracking-[0.5em] uppercase mb-2 font-bold">Compliance Requirements</h4>
                <h3 className="heading-font text-2xl md:text-3xl font-bold text-slate-900 tracking-tight">
                  Mandatory <span className="text-euro-600">Verification</span>
                </h3>
                <p className="text-slate-400 text-xs mt-1 italic">*Not exhaustive</p>
              </div>
              <div className="space-y-4">
                {mandatoryVerification.map((item, i) => (
                  <div key={i} className="flex items-start gap-4 p-5 rounded-2xl border border-slate-100 bg-[#f8fafc] hover:border-euro-200 transition-all duration-300">
                    <div className="w-10 h-10 rounded-xl bg-euro-50 flex items-center justify-center text-euro-600 shrink-0">
                      <i className={`fas ${item.icon} text-sm`}></i>
                    </div>
                    <p className="text-slate-600 text-sm leading-relaxed pt-2">{item.text}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Benefits of BRSR verification from Eurocert */}
            <div>
              <div className="mb-6">
                <h4 className="heading-font text-[11px] text-euro-600 tracking-[0.5em] uppercase mb-2 font-bold">Eurocert Advantage</h4>
                <h3 className="heading-font text-2xl md:text-3xl font-bold text-slate-900 tracking-tight">
                  Benefits of BRSR Verification <span className="text-euro-600">from Eurocert SA</span>
                </h3>
              </div>
              <div className="space-y-4">
                {eurocertBenefits.map((item, i) => (
                  <div key={i} className="flex items-start gap-4 p-5 rounded-2xl border border-slate-100 bg-[#f8fafc] hover:border-euro-200 transition-all duration-300">
                    <div className="w-10 h-10 rounded-xl bg-euro-50 flex items-center justify-center text-euro-600 shrink-0">
                      <i className={`fas ${item.icon} text-sm`}></i>
                    </div>
                    <p className="text-slate-600 text-sm leading-relaxed pt-2">{item.text}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* How Eurocert SA Assist - Dark */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-[#030a16]"></div>
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,rgba(212,168,67,0.06)_0%,transparent_60%)]"></div>
        <div className="relative z-10 py-14 lg:py-18">
          <div className="container mx-auto px-6">
            <div className="max-w-5xl mx-auto">
              <div className="text-center mb-10">
                <h4 className="heading-font text-[11px] text-eurogold-400 tracking-[0.5em] uppercase mb-2 font-bold">Our Approach</h4>
                <h3 className="heading-font text-3xl md:text-4xl font-bold text-white tracking-tight">
                  How Eurocert SA <span className="text-eurogold-400">Assist & Work</span>
                </h3>
              </div>

              {/* Core Verification Services */}
              <div className="grid lg:grid-cols-2 gap-6 mb-8">
                {verificationServices.map((s, i) => (
                  <div key={i} className="p-8 rounded-2xl border border-white/5 bg-white/2 hover:border-eurogold-400/20 transition-all duration-300">
                    <div className="flex items-center gap-3 mb-4">
                      <div className="w-10 h-10 rounded-xl bg-eurogold-400/10 flex items-center justify-center">
                        <i className={`fas ${s.icon} text-eurogold-400 text-sm`}></i>
                      </div>
                      <h4 className="heading-font text-white font-bold text-sm uppercase tracking-widest">{s.title}</h4>
                    </div>
                    <p className="text-white/50 text-sm leading-relaxed">{s.desc}</p>
                  </div>
                ))}
              </div>

              {/* Assessment & Verification Areas */}
              <div className="mb-6">
                <p className="text-center text-white/60 text-sm mb-6">In addition, Eurocert SA is competent to assess and verify your:</p>
              </div>
              <div className="grid lg:grid-cols-3 gap-5 mb-8">
                {assessmentAreas.map((a, i) => (
                  <div key={i} className="p-6 rounded-2xl border border-white/5 bg-white/2 hover:border-eurogold-400/20 transition-all duration-300 text-center">
                    <div className="w-12 h-12 rounded-xl bg-eurogold-400/10 flex items-center justify-center mx-auto mb-4">
                      <i className={`fas ${a.icon} text-eurogold-400 text-base`}></i>
                    </div>
                    <h4 className="heading-font text-white font-bold text-[11px] uppercase tracking-widest mb-2">{a.title}</h4>
                    <p className="text-white/45 text-sm leading-relaxed">{a.desc}</p>
                  </div>
                ))}
              </div>

              {/* Individual Verification Items */}
              <div className="p-8 rounded-2xl border border-white/5 bg-white/2">
                <h4 className="heading-font text-eurogold-400 font-bold text-[11px] uppercase tracking-widest mb-6 text-center">Individual Verification Scope</h4>
                <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
                  {individualVerificationItems.map((item, i) => (
                    <div key={i} className="flex items-center gap-3 p-3 rounded-xl border border-white/5 hover:border-eurogold-400/20 transition-all">
                      <div className="w-8 h-8 rounded-lg bg-eurogold-400/10 flex items-center justify-center shrink-0">
                        <i className={`fas ${item.icon} text-eurogold-400 text-xs`}></i>
                      </div>
                      <span className="text-white/60 text-sm">{item.text}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Eurocert SA banner */}
              <div className="p-5 mt-8 rounded-xl border border-eurogold-400/20 bg-eurogold-400/5 text-center">
                <p className="text-white/60 text-sm leading-relaxed">
                  <span className="text-eurogold-400 font-bold">We are offering above services on behalf of Eurocert S.A</span> — a Pan-European Certification body operating from Athens with global reach.
                </p>
              </div>

              <div className="grid grid-cols-3 gap-4 mt-6">
                <div className="p-5 rounded-xl border border-eurogold-400/20 bg-eurogold-400/5 text-center">
                  <span className="heading-font text-eurogold-400 font-bold text-3xl block mb-1 leading-none">14+</span>
                  <span className="text-[9px] font-bold text-white/50 uppercase tracking-[0.2em] heading-font">Countries</span>
                </div>
                <div className="p-5 rounded-xl border border-eurogold-400/20 bg-eurogold-400/5 text-center">
                  <span className="heading-font text-eurogold-400 font-bold text-3xl block mb-1 leading-none">25+</span>
                  <span className="text-[9px] font-bold text-white/50 uppercase tracking-[0.2em] heading-font">Years Experience</span>
                </div>
                <div className="p-5 rounded-xl border border-eurogold-400/20 bg-eurogold-400/5 text-center">
                  <span className="heading-font text-eurogold-400 font-bold text-3xl block mb-1 leading-none">100%</span>
                  <span className="text-[9px] font-bold text-white/50 uppercase tracking-[0.2em] heading-font">Success Rate</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Related Services - Soft BG */}
      <section className="py-14 lg:py-18 bg-[#f8fafc]">
        <div className="container mx-auto px-6">
          <div className="text-center mb-8">
            <h4 className="heading-font text-[11px] text-euro-600 tracking-[0.5em] uppercase mb-2 font-bold">Explore More</h4>
            <h2 className="heading-font text-3xl md:text-4xl font-bold text-slate-900 tracking-tight">Related Certifications</h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-5 max-w-4xl mx-auto">
            {relatedServices.map((s, i) => (
              <Link key={i} to={s.link} className="group relative h-[280px] rounded-2xl overflow-hidden border border-slate-200 hover:border-euro-300 shadow-md hover:shadow-xl transition-all duration-500">
                <div className="absolute inset-0 bg-cover bg-center transition-transform duration-700 group-hover:scale-110" style={{ backgroundImage: `url('${s.image}')` }} />
                <div className="absolute inset-0 bg-linear-to-t from-[#030a16]/80 via-[#030a16]/20 to-transparent"></div>
                <div className="absolute bottom-5 left-5 right-5 z-20">
                  <h4 className="text-white text-sm heading-font font-bold uppercase tracking-widest mb-1">{s.title}</h4>
                  <span className="text-[9px] font-bold uppercase text-eurogold-400 tracking-[0.2em] heading-font">{s.subtitle}</span>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* CTA - Dark */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-[#030a16]"></div>
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_bottom,rgba(212,168,67,0.06)_0%,transparent_60%)]"></div>
        <div className="relative z-10 py-14 lg:py-18">
          <div className="container mx-auto px-6 text-center">
            <div className="max-w-2xl mx-auto p-10 sm:p-12 rounded-2xl border border-white/5 bg-white/2">
              <h4 className="heading-font text-[11px] text-eurogold-400 tracking-[0.5em] uppercase mb-3 font-bold">Get Verified</h4>
              <h2 className="heading-font text-2xl sm:text-3xl md:text-4xl font-bold text-white tracking-tight mb-4">Start Your BRSR Journey</h2>
              <p className="text-white/45 mb-6 max-w-lg mx-auto text-sm leading-relaxed">Our ESG and sustainability experts are ready to guide your organization through BRSR verification and compliance.</p>
              <div className="flex flex-col sm:flex-row gap-3 justify-center">
                <Link to="/contact" className="inline-flex items-center justify-center gap-2 heading-font text-[11px] font-bold uppercase tracking-[0.2em] text-[#030a16] bg-eurogold-400 rounded-full px-8 py-3.5 hover:bg-eurogold-300 transition-all shadow-lg shadow-eurogold-400/20">
                  Get Started <i className="fas fa-arrow-right text-[9px]"></i>
                </Link>
                <a href="tel:+917009007527" className="inline-flex items-center justify-center gap-2 heading-font text-[11px] font-bold uppercase tracking-[0.2em] text-white border border-white/15 rounded-full px-8 py-3.5 hover:bg-white/5 transition-all">
                  <i className="fas fa-phone text-[9px]"></i> Call Us Now
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  )
}
